Repository timemates/backend, pull requests merged in 2023-06, with the labels that each got.

#125 feat (#99): replace createOrThrow with createOrAssert
  data/build.gradle.kts
  data/src/test/kotlin/io/timemates/backend/data/files/FileEntityMapperTest.kt
  data/src/test/kotlin/io/timemates/backend/data/users/UserEntitiesMapperTest.kt
  data/src/test/kotlin/io/timemates/backend/data/users/UsersRepositoryTest.kt
  domain/build.gradle.kts
  domain/src/test/kotlin/io/timemates/backend/auth/usecases/AuthByEmailUseCaseTest.kt
  domain/src/test/kotlin/io/timemates/backend/auth/usecases/ConfigureNewAccountUseCaseTest.kt
  features/test-utils/src/main/kotlin/io/timemates/backend/testing/validation/createOrAssert.kt
Labels: refactor, tests

#136 feat (#123): better explanation of value object that is passed as empty or default by gRPC
  domain/src/main/kotlin/io/timemates/backend/authorization/types/value/AccessHash.kt
  domain/src/main/kotlin/io/timemates/backend/authorization/types/value/RefreshHash.kt
  domain/src/main/kotlin/io/timemates/backend/authorization/types/value/VerificationCode.kt
  domain/src/main/kotlin/io/timemates/backend/files/types/value/FileId.kt
  domain/src/main/kotlin/io/timemates/backend/timers/types/value/InviteCode.kt
  domain/src/main/kotlin/io/timemates/backend/timers/types/value/TimerName.kt
  domain/src/main/kotlin/io/timemates/backend/users/types/value/EmailAddress.kt
  domain/src/main/kotlin/io/timemates/backend/users/types/value/UserName.kt
Labels: feature

#141 fix (#140): authorization interceptor is registering now
  infrastructure/application/src/main/kotlin/io/timemates/backend/application/Application.kt
Labels: bug

#145 refactor (#138): `setTimerInfo` and `setTimerSettings` are merged into one RPC
  domain/src/main/kotlin/io/timemates/backend/timers/usecases/SetTimerInfoUseCase.kt
  infrastructure/services/src/main/kotlin/io/timemates/backend/services/timers/GrpcTimersMapper.kt
  infrastructure/services/src/main/kotlin/io/timemates/backend/services/timers/TimersService.kt
  infrastructure/services/src/main/proto/io/timemates/api/timers/TimersService.proto
  infrastructure/services/src/main/proto/io/timemates/api/timers/requests/EditTimerInfoRequest.proto
  infrastructure/services/src/main/proto/io/timemates/api/timers/requests/EditTimerSettingsRequest.proto
  infrastructure/services/src/main/proto/io/timemates/api/timers/types/Timer.proto
Labels: refactor

#144 refactor (#139): upload file api
  data/src/main/kotlin/io/timemates/backend/data/files/FilesRepository.kt
  data/src/main/kotlin/io/timemates/backend/data/files/datasource/FileEntityMapper.kt
  data/src/main/kotlin/io/timemates/backend/data/files/datasource/LocalFilesDataSource.kt
  domain/src/main/kotlin/io/timemates/backend/files/repositories/FilesRepository.kt
  domain/src/main/kotlin/io/timemates/backend/files/types/FileType.kt
  domain/src/main/kotlin/io/timemates/backend/files/usecases/UploadFileUseCase.kt
  infrastructure/application/src/main/kotlin/io/timemates/backend/application/dependencies/FilesModule.kt
  infrastructure/services/src/main/kotlin/io/timemates/backend/services/files/FilesService.kt
  infrastructure/services/src/main/proto/io/timemates/api/files/requests/UploadFileRequest.proto
Labels: refactor

#147 refactor(#13(4+3)): Optimize koin dependencies declarations
  app/src/main/kotlin/io/timemates/backend/application/dependencies/AuthorizationsModule.kt
  app/src/main/kotlin/io/timemates/backend/application/dependencies/CommonModule.kt
  app/src/main/kotlin/io/timemates/backend/application/dependencies/ServicesModule.kt
  app/src/main/kotlin/io/timemates/backend/application/dependencies/TimersModule.kt
  app/src/main/kotlin/io/timemates/backend/application/dependencies/UsersModule.kt
Labels: refactor
